from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_anthropic import ChatAnthropic
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
import anthropic
import json
import os
from typing import Optional, Generator

VECTORSTORE_PATH = './vectorstore'

memory = ConversationBufferMemory(
    memory_key='chat_history',
    return_messages=True,
    output_key='answer'
)


def generate_hypothetical_answer(question: str) -> str:
    """
    Generate a hypothetical answer to a question using Claude (HyDE technique).

    Instead of searching the vector store with the raw question, HyDE first
    generates a plausible answer and uses that as the search query. This improves
    retrieval quality because a hypothetical answer is semantically closer to
    real document chunks than the question itself.

    Args:
        question (str): The user's question.

    Returns:
        str: A hypothetical answer generated by Claude, used as retrieval query.
    """
    client = anthropic.Anthropic(api_key=os.environ.get('ANTHROPIC_API_KEY'))
    response = client.messages.create(
        model='claude-sonnet-4-5',
        max_tokens=256,
        messages=[{
            'role': 'user',
            'content': (
                'Generate a short hypothetical answer to the following question. '
                'Write it as if it were a passage from a technical document. '
                'Do not say you are generating a hypothetical answer, just write the passage.\n\n'
                'Question: ' + question
            )
        }]
    )
    return response.content[0].text


def query_rag(question: str, filter_document: Optional[str] = None, use_hyde: bool = True) -> dict:
    """
    Execute the full RAG pipeline for a given question with conversation memory.

    Optionally applies HyDE to improve retrieval quality by generating a
    hypothetical answer and using it as the search query.

    Args:
        question (str): The natural language question asked by the user.
        filter_document (Optional[str]): If provided, restricts retrieval to chunks
            from this specific document filename. If None, searches all documents.
        use_hyde (bool): Whether to apply HyDE for retrieval. Default is True.

    Returns:
        dict: A dictionary with 'answer' and 'sources' keys.
    """
    embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')
    vectorstore = FAISS.load_local(VECTORSTORE_PATH, embeddings, allow_dangerous_deserialization=True)

    search_query = generate_hypothetical_answer(question) if use_hyde else question

    if filter_document:
        retriever = vectorstore.as_retriever(
            search_kwargs={'k': 4, 'filter': {'source_filename': filter_document}}
        )
    else:
        retriever = vectorstore.as_retriever(search_kwargs={'k': 4})

    relevant_docs = retriever.invoke(search_query)

    llm = ChatAnthropic(
        model='claude-sonnet-4-5',
        temperature=0,
        api_key=os.environ.get('ANTHROPIC_API_KEY')
    )

    qa_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=retriever,
        memory=memory,
        return_source_documents=True,
        output_key='answer'
    )

    result = qa_chain.invoke({'question': question})

    return {
        'answer': result['answer'],
        'sources': [doc.page_content[:200] for doc in result['source_documents']]
    }


def stream_rag(question: str, filter_document: Optional[str] = None, use_hyde: bool = True) -> Generator:
    """
    Execute the RAG pipeline and stream the response token by token using SSE.

    Optionally applies HyDE to improve retrieval quality before streaming.

    Args:
        question (str): The natural language question asked by the user.
        filter_document (Optional[str]): If provided, restricts retrieval to chunks
            from this specific document filename.
        use_hyde (bool): Whether to apply HyDE for retrieval. Default is True.

    Yields:
        str: SSE-formatted strings with individual tokens, sources, and a done event.
    """
    embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')
    vectorstore = FAISS.load_local(VECTORSTORE_PATH, embeddings, allow_dangerous_deserialization=True)

    search_query = generate_hypothetical_answer(question) if use_hyde else question

    if filter_document:
        retriever = vectorstore.as_retriever(
            search_kwargs={'k': 4, 'filter': {'source_filename': filter_document}}
        )
    else:
        retriever = vectorstore.as_retriever(search_kwargs={'k': 4})

    docs = retriever.invoke(search_query)
    context = '\n\n'.join([doc.page_content for doc in docs])
    sources = [doc.page_content[:200] for doc in docs]

    prompt = (
        'You are a helpful assistant that answers questions exclusively based on the provided document context.\n'
        'If the answer is not in the context, say so clearly.\n\n'
        'Context:\n' + context + '\n\n'
        'Question: ' + question + '\n\nAnswer:'
    )

    client = anthropic.Anthropic(api_key=os.environ.get('ANTHROPIC_API_KEY'))

    with client.messages.stream(
        model='claude-sonnet-4-5',
        max_tokens=1024,
        messages=[{'role': 'user', 'content': prompt}]
    ) as stream:
        for text in stream.text_stream:
            yield 'data: ' + text + '\n\n'

    yield 'event: sources\ndata: ' + json.dumps(sources) + '\n\n'
    yield 'event: done\ndata: \n\n'


def clear_memory() -> None:
    """
    Reset the conversation memory.
    """
    memory.clear()